version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
       - "5001:5001"

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "8000:3000"

  